version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
    expose:
      - "9200"
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    volumes:
      - static-root:/code/bakerydemo/collect_static
      - media-root:/code/bakerydemo/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
      - elasticsearch

  nginx:
    restart: always
    volumes:
      - media-root:/code/bakerydemo/media
      - static-root:/code/bakerydemo/static
    build:
     context: .
     dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
     - app
    ports:
      - "8080:8080"

volumes:
  media-root:
  static-root: