# this file is used to start containers on remote server

version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    image: "$DB_IMAGE"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  redis:
    image: "$REDIS_IMAGE"
    expose:
      - "6379"
  elasticsearch:
    image: "$ELASTIC_IMAGE"
    expose:
      - "9200"
  app:
    image: "${WEB_IMAGE}"
    environment:
      DJANGO_ALLOWED_HOSTS: 5.63.154.150 localhost 127.0.0.1 [::1]
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    volumes:
      - static-root:/code/bakerydemo/collect_static
      - media-root:/code/bakerydemo/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
      - elasticsearch

  nginx:
    volumes:
      - media-root:/code/bakerydemo/media
      - static-root:/code/bakerydemo/static
    image: "${NGINX_IMAGE}"
    depends_on:
     - app
    ports:
      - "80:80"

volumes:
  media-root:
  static-root:
  postgres_data: